# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: couponmanage.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ouponmanage.proto\x12\x0c\x63ouponmanage\"\xab\x01\n\rOperatingInfo\x12\x38\n\x14open_day_of_the_week\x18\x01 \x01(\x0e\x32\x1a.couponmanage.DayOfTheWeek\x12\x11\n\topen_hour\x18\x02 \x01(\t\x12\x39\n\x15\x63lose_day_of_the_week\x18\x03 \x01(\x0e\x32\x1a.couponmanage.DayOfTheWeek\x12\x12\n\nclose_hour\x18\x04 \x01(\t\"p\n\nCafeDetail\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\x33\n\x0eoperating_info\x18\x04 \x03(\x0b\x32\x1b.couponmanage.OperatingInfo\"\xc8\x01\n\x11\x43\x61\x66\x65UpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\x33\n\x0eoperating_info\x18\x04 \x03(\x0b\x32\x1b.couponmanage.OperatingInfo\x12\x17\n\x0fis_address_null\x18\x05 \x01(\x08\x12\x16\n\x0eis_rating_null\x18\x06 \x01(\x08\x12\x1e\n\x16is_operating_info_null\x18\x07 \x01(\x08\"7\n\x0c\x41llCafeReply\x12\'\n\x05\x63\x61\x66\x65s\x18\x01 \x03(\x0b\x32\x18.couponmanage.CafeDetail\"!\n\x11\x43\x61\x66\x65\x44\x65tailRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"\x0c\n\nEmptyReply\"0\n\x1a\x43\x61\x66\x65RegisterAndUpdateReply\x12\x12\n\nis_success\x18\x01 \x01(\x08*M\n\x0c\x44\x61yOfTheWeek\x12\x07\n\x03SUN\x10\x00\x12\x07\n\x03MON\x10\x01\x12\x07\n\x03TUE\x10\x02\x12\x07\n\x03WED\x10\x03\x12\x07\n\x03THU\x10\x04\x12\x07\n\x03\x46RI\x10\x05\x12\x07\n\x03SAT\x10\x06\x32\xdf\x02\n\rCouponManager\x12T\n\x0cRegisterCafe\x12\x18.couponmanage.CafeDetail\x1a(.couponmanage.CafeRegisterAndUpdateReply\"\x00\x12K\n\x0fReceiveAllCafes\x12\x1a.couponmanage.EmptyRequest\x1a\x1a.couponmanage.AllCafeReply\"\x00\x12P\n\x11ReceiveCafeDetail\x12\x1f.couponmanage.CafeDetailRequest\x1a\x18.couponmanage.CafeDetail\"\x00\x12Y\n\nUpdateCafe\x12\x1f.couponmanage.CafeUpdateRequest\x1a(.couponmanage.CafeRegisterAndUpdateReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'couponmanage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DAYOFTHEWEEK']._serialized_start=699
  _globals['_DAYOFTHEWEEK']._serialized_end=776
  _globals['_OPERATINGINFO']._serialized_start=37
  _globals['_OPERATINGINFO']._serialized_end=208
  _globals['_CAFEDETAIL']._serialized_start=210
  _globals['_CAFEDETAIL']._serialized_end=322
  _globals['_CAFEUPDATEREQUEST']._serialized_start=325
  _globals['_CAFEUPDATEREQUEST']._serialized_end=525
  _globals['_ALLCAFEREPLY']._serialized_start=527
  _globals['_ALLCAFEREPLY']._serialized_end=582
  _globals['_CAFEDETAILREQUEST']._serialized_start=584
  _globals['_CAFEDETAILREQUEST']._serialized_end=617
  _globals['_EMPTYREQUEST']._serialized_start=619
  _globals['_EMPTYREQUEST']._serialized_end=633
  _globals['_EMPTYREPLY']._serialized_start=635
  _globals['_EMPTYREPLY']._serialized_end=647
  _globals['_CAFEREGISTERANDUPDATEREPLY']._serialized_start=649
  _globals['_CAFEREGISTERANDUPDATEREPLY']._serialized_end=697
  _globals['_COUPONMANAGER']._serialized_start=779
  _globals['_COUPONMANAGER']._serialized_end=1130
# @@protoc_insertion_point(module_scope)
